# Generated by Django 4.1.5 on 2023-01-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uploaded',
            new_name='updated',
        ),
    ]
